### ISSUE TITLE
Change project name to something meaningful

### ISSUE THREAD

**Issue by vwbusguy** [azusapacificuniversity/scripts#1]
Since this is a shared organizational space, it might be beneficial to rename this to something more specific, such as "misc-client-automation-scripts".

**Comment by ParadoxGuitarist** [comment]
misc-client-automation-scripts would be appropriate if that's all that we would ever put here. I would hope that we could put more than just client automation scripts here. The initial thought was if you had scripted a small program that might be worth sharing, but not worth setting up it's own repository for, the shared org can dump them here. We can always re-arrange the structure to differentiate between client-automation scripts and other types as they become included.  

I don't feel strongly about it, but if you'd rather us get specific and set up multiple repos, we certainly could. We could even break this one up into 3 or 4, but that just seemed excessive to me.

**Comment by ParadoxGuitarist** [comment]
Closed due to lack of discussion.
